import { Router } from "express";
import { MenuKey } from "@complaint-system/shared";
import { authRoutes } from "./authRoutes";
import { caseRoutes } from "./caseRoutes";
import { customerRoutes } from "./customerRoutes";
import { userRoutes } from "./userRoutes";
import { healthRoutes } from "./healthRoutes";
import { settingsRoutes } from "./settingsRoutes";
import { orderRoutes } from "./orderRoutes";
import { logRoutes } from "./logRoutes";
import { packageRoutes } from "./packageRoutes";
import { purchasingOverviewRoutes } from "./purchasingOverviewRoutes";
import { receivingRoutes } from "./receivingRoutes";
import { shopfaProductRoutes } from "./shopfaProductRoutes";
import { devToolsRoutes } from "./devToolsRoutes";
import { reportingRoutes } from "./reportingRoutes";
import { orderPrecheckRoutes } from "./orderPrecheckRoutes";
import { packingRoutes } from "./packingRoutes";
import { ordersByStatusRoutes } from "./ordersByStatusRoutes";
import { requireAnyReportAccess, requireAuth, requirePermission } from "../middleware/authenticate";

export const apiRouter = Router();

apiRouter.use("/health", healthRoutes);
apiRouter.use("/auth", authRoutes);
apiRouter.use("/cases", requireAuth, requirePermission(MenuKey.CASES), caseRoutes);
apiRouter.use("/customers", requireAuth, requirePermission(MenuKey.CASES), customerRoutes);
apiRouter.use("/users", requireAuth, userRoutes);
apiRouter.use("/settings", requireAuth, requirePermission(MenuKey.SETTINGS), settingsRoutes);
apiRouter.use("/orders", requireAuth, requirePermission(MenuKey.SETTINGS), orderRoutes);
apiRouter.use("/logs", requireAuth, requirePermission(MenuKey.LOGS), logRoutes);
apiRouter.use("/packages", requireAuth, requirePermission(MenuKey.PURCHASING), packageRoutes);
apiRouter.use("/purchasing/overview", requireAuth, requirePermission(MenuKey.PURCHASING), purchasingOverviewRoutes);
apiRouter.use("/receiving", requireAuth, requirePermission(MenuKey.RECEIVING), receivingRoutes);
apiRouter.use("/shopfa/products", requireAuth, requirePermission(MenuKey.PURCHASING), shopfaProductRoutes);
apiRouter.use("/dev-tools", requireAuth, requirePermission(MenuKey.DEV_TOOLS), devToolsRoutes);
apiRouter.use("/reporting", requireAuth, requireAnyReportAccess, reportingRoutes);
apiRouter.use("/order-precheck", requireAuth, requirePermission(MenuKey.ORDER_CHECK), orderPrecheckRoutes);
apiRouter.use("/packing", requireAuth, requirePermission(MenuKey.PACKING), packingRoutes);
apiRouter.use("/order-status", requireAuth, requirePermission(MenuKey.ORDERS_BY_STATUS), ordersByStatusRoutes);
